server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false # default true

  # 파일 크기
  servlet:
    multipart:
      # total file size cannot exceed 10MB.
      max-file-size: 10MB
      # total request size for a multipart/form-data cannot exceed 20MB.
      max-request-size: 20MB

  #JPA Pageable global 설정
  data:
    web:
      pageable:
        default-page-size: 10

# 파일 관련
resources:
  location: D:/upload/@project.name@/
  uri_path: /images/**